---
sidebar: sidebar 
permalink: trident-docker/collect-logs-docker.html 
keywords: deploy, Trident, trident for docker, docker, logs, binary, managed plugin 
summary: 문제 해결에 도움이 되도록 로그를 수집할 수 있습니다. 로그 수집 방법은 Docker 플러그인을 실행하는 방식에 따라 다릅니다. 
---
= 로그 수집
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
문제 해결에 도움이 되도록 로그를 수집할 수 있습니다. 로그 수집 방법은 Docker 플러그인을 실행하는 방식에 따라 다릅니다.



== 문제 해결을 위해 로그를 수집합니다

.단계
. 권장되는 관리형 플러그인 방식(즉,  `docker plugin` 명령을 사용)을 사용하여 Trident를 실행하는 경우 다음과 같이 확인합니다.
+
[source, console]
----
docker plugin ls
----
+
[listing]
----
ID                  NAME                DESCRIPTION                          ENABLED
4fb97d2b956b        netapp:latest       nDVP - NetApp Docker Volume Plugin   false
journalctl -u docker | grep 4fb97d2b956b
----
+
기본 로깅 수준을 사용하면 대부분의 문제를 진단할 수 있습니다. 만약 그것으로 충분하지 않다고 판단되면 디버그 로깅을 활성화할 수 있습니다.

. 디버그 로깅을 활성화하려면 디버그 로깅이 활성화된 플러그인을 설치하십시오.
+
[source, console]
----
docker plugin install netapp/trident-plugin:<version> --alias <alias> debug=true
----
+
또는 플러그인이 이미 설치된 경우 디버그 로깅을 활성화하십시오.

+
[source, console]
----
docker plugin disable <plugin>
----
+
[source, console]
----
docker plugin set <plugin> debug=true
----
+
[source, console]
----
docker plugin enable <plugin>
----
. 호스트에서 바이너리 자체를 실행하는 경우 로그는 호스트의 `/var/log/netappdvp` 디렉터리에서 확인할 수 있습니다. 디버그 로깅을 활성화하려면 플러그인을 실행할 때 `-debug`를 지정하십시오.




== 일반적인 문제 해결 팁

* 새로운 사용자들이 가장 흔히 겪는 문제는 플러그인 초기화를 방해하는 잘못된 구성입니다. 이러한 경우 플러그인을 설치하거나 활성화하려고 할 때 다음과 같은 메시지가 표시될 수 있습니다:
+
`Error response from daemon: dial unix /run/docker/plugins/<id>/netapp.sock: connect: no such file or directory`

+
이는 플러그인이 시작되지 않았음을 의미합니다. 다행히 이 플러그인은 포괄적인 로깅 기능을 갖추고 있어 발생할 수 있는 대부분의 문제를 진단하는 데 도움이 될 것입니다.

* 컨테이너에 PV를 마운트하는 데 문제가 있는 경우 `rpcbind`가 설치되어 실행 중인지 확인하십시오. 호스트 OS에 필요한 패키지 관리자를 사용하여 `rpcbind`가 실행 중인지 확인하십시오. rpcbind 서비스의 상태는 `systemctl status rpcbind` 또는 이와 동등한 명령을 실행하여 확인할 수 있습니다.

