---
sidebar: sidebar 
permalink: trident-docker/prereqs-docker.html 
keywords: deploy, Trident, docker, trident for docker, nfs, iscsi, protcol, nfs protocol, iscsi protocol, configure host, host config, nvme/tcp, fc, nvme 
summary: Trident를 배포하기 전에 호스트에 필요한 프로토콜 사전 요구 사항을 설치하고 구성해야 합니다. 
---
= 배포를 위한 사전 요구 사항
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Trident를 배포하기 전에 호스트에 필요한 프로토콜 사전 요구 사항을 설치하고 구성해야 합니다.



== 요구 사항을 확인하십시오

* 배포가 모든 link:../trident-get-started/requirements.html["요구사항"]를 충족하는지 확인하십시오.
* 지원되는 버전의 Docker가 설치되어 있는지 확인하십시오. Docker 버전이 최신 버전이 아닌 경우 https://docs.docker.com/engine/install/["설치하거나 업데이트하십시오"^].
+
[source, console]
----
docker --version
----
* 프로토콜 사전 요구 사항이 호스트에 설치 및 구성되었는지 확인하십시오.




=== NFS 도구

사용 중인 운영 체제에 맞는 명령을 사용하여 NFS 툴을 설치합니다.

[role="tabbed-block"]
====
.RHEL 8+
--
[source, console]
----
sudo yum install -y nfs-utils
----
--
.Ubuntu
--
[source, console]
----
sudo apt-get install -y nfs-common
----
--
====

WARNING: NFS 도구를 설치한 후 워커 노드를 재부팅하여 컨테이너에 볼륨을 연결할 때 발생하는 오류를 방지하십시오.



=== iSCSI 도구

운영 체제에 맞는 명령을 사용하여 iSCSI 툴을 설치합니다.

[role="tabbed-block"]
====
.RHEL 8+
--
. 다음 시스템 패키지를 설치하십시오.
+
[source, console]
----
sudo yum install -y lsscsi iscsi-initiator-utils sg3_utils device-mapper-multipath
----
. iscsi-initiator-utils 버전이 6.2.0.874-2.el7 이상인지 확인하십시오.
+
[source, console]
----
rpm -q iscsi-initiator-utils
----
. 스캔을 수동으로 설정:
+
[source, console]
----
sudo sed -i 's/^\(node.session.scan\).*/\1 = manual/' /etc/iscsi/iscsid.conf
----
. 다중 경로 지정 활성화:
+
[source, console]
----
sudo mpathconf --enable --with_multipathd y --find_multipaths n
----
+

NOTE: 반드시 `etc/multipath.conf`에 `find_multipaths no`가 `defaults` 아래에 포함되어 있는지 확인하십시오.

.  `iscsid` 및  `multipathd`가 실행 중인지 확인하십시오.
+
[source, console]
----
sudo systemctl enable --now iscsid multipathd
----
. 활성화 및 시작 `iscsi`:
+
[source, console]
----
sudo systemctl enable --now iscsi
----


--
.Ubuntu
--
. 다음 시스템 패키지를 설치하십시오.
+
[source, console]
----
sudo apt-get install -y open-iscsi lsscsi sg3-utils multipath-tools scsitools
----
. open-iscsi 버전이 2.0.874-5ubuntu2.10 이상(bionic의 경우) 또는 2.0.874-7.1ubuntu6.1 이상(focal의 경우)인지 확인하십시오.
+
[source, console]
----
dpkg -l open-iscsi
----
. 스캔을 수동으로 설정:
+
[source, console]
----
sudo sed -i 's/^\(node.session.scan\).*/\1 = manual/' /etc/iscsi/iscsid.conf
----
. 다중 경로 지정 활성화:
+
[source, console]
----
sudo tee /etc/multipath.conf <<-EOF
defaults {
    user_friendly_names yes
    find_multipaths no
}
EOF
sudo systemctl enable --now multipath-tools.service
sudo service multipath-tools restart
----
+

NOTE: 반드시 `etc/multipath.conf`에 `find_multipaths no`가 `defaults` 아래에 포함되어 있는지 확인하십시오.

.  `open-iscsi` 및  `multipath-tools`가 활성화되어 실행 중인지 확인하십시오.
+
[source, console]
----
sudo systemctl status multipath-tools
sudo systemctl enable --now open-iscsi.service
sudo systemctl status open-iscsi
----


--
====


== NVMe 도구

사용 중인 운영 체제에 맞는 명령을 사용하여 NVMe 툴을 설치하십시오.

[NOTE]
====
* NVMe에는 RHEL 9 이상이 필요합니다.
* Kubernetes 노드의 커널 버전이 너무 오래되었거나 해당 커널 버전에 맞는 NVMe 패키지를 사용할 수 없는 경우 노드의 커널 버전을 NVMe 패키지가 포함된 버전으로 업데이트해야 할 수 있습니다.


====
[role="tabbed-block"]
====
.RHEL 9
--
[source, console]
----
sudo yum install nvme-cli
sudo yum install linux-modules-extra-$(uname -r)
sudo modprobe nvme-tcp
----
--
.Ubuntu
--
[source, console]
----
sudo apt install nvme-cli
sudo apt -y install linux-modules-extra-$(uname -r)
sudo modprobe nvme-tcp
----
--
====


== FC 툴

운영 체제에 대한 명령을 사용하여 FC 툴을 설치합니다.

* FC PV를 사용하는 RHEL/Red Hat Enterprise Linux CoreOS(RHCOS) 워커 노드를 사용할 때, 인라인 공간 재확보를 수행하려면  `discard` StorageClass에서 mountOption을 지정하십시오.  https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_file_systems/discarding-unused-blocks_managing-file-systems["Red Hat 문서"^]를 참조하십시오.


[role="tabbed-block"]
====
.RHEL 8+
--
. 다음 시스템 패키지를 설치하십시오.
+
[source, console]
----
sudo yum install -y lsscsi device-mapper-multipath
----
. 다중 경로 지정 활성화:
+
[source, console]
----
sudo mpathconf --enable --with_multipathd y --find_multipaths n
----
+

NOTE: 반드시 `etc/multipath.conf`에 `find_multipaths no`가 `defaults` 아래에 포함되어 있는지 확인하십시오.

.  `multipathd`이(가) 실행 중인지 확인하십시오.
+
[source, console]
----
sudo systemctl enable --now multipathd
----


--
.Ubuntu
--
. 다음 시스템 패키지를 설치하십시오.
+
[source, console]
----
sudo apt-get install -y lsscsi sg3-utils multipath-tools scsitools
----
. 다중 경로 지정 활성화:
+
[source, console]
----
sudo tee /etc/multipath.conf <<-EOF
defaults {
    user_friendly_names yes
    find_multipaths no
}
EOF
sudo systemctl enable --now multipath-tools.service
sudo service multipath-tools restart
----
+

NOTE: 반드시 `etc/multipath.conf`에 `find_multipaths no`가 `defaults` 아래에 포함되어 있는지 확인하십시오.

.  `multipath-tools`이(가) 활성화되어 실행 중인지 확인하십시오.
+
[source, console]
----
sudo systemctl status multipath-tools
----


--
====