---
sidebar: sidebar 
permalink: trident-docker/volume-driver-options.html 
keywords: create volumes, Trident, trident for docker, docker, docker volume, driver options, ontap, element volumes, azure netapp files 
summary: 각 스토리지 드라이버는 볼륨 생성 시 지정할 수 있는 다양한 옵션 세트를 제공하여 결과물을 사용자 지정할 수 있습니다. 구성된 스토리지 시스템에 적용되는 옵션은 아래를 참조하십시오. 
---
= 드라이버별 볼륨 옵션
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
각 스토리지 드라이버는 볼륨 생성 시 지정할 수 있는 다양한 옵션 세트를 제공하여 결과물을 사용자 지정할 수 있습니다. 구성된 스토리지 시스템에 적용되는 옵션은 아래를 참조하십시오.

볼륨 생성 작업 중에 이러한 옵션을 사용하는 것은 간단합니다. CLI 작업 중에 `-o` 연산자를 사용하여 옵션과 값을 제공합니다. 이러한 값은 JSON 구성 파일의 동등한 값을 재정의합니다.



== ONTAP 볼륨 옵션

NFS, iSCSI 및 FC에 대한 볼륨 생성 옵션은 다음과 같습니다.

[cols="2*"]
|===
| 옵션 | 설명 


| `size`  a| 
볼륨의 크기로, 기본값은 1GiB입니다.



| `spaceReserve`  a| 
볼륨을 씬 프로비저닝 또는 씩 프로비저닝할지 결정하며, 기본값은 씬 프로비저닝입니다. 유효한 값은 `none`(씬 프로비저닝)과 `volume`(씩 프로비저닝)입니다.



| `snapshotPolicy`  a| 
이렇게 하면 스냅샷 정책이 원하는 값으로 설정됩니다. 기본값은 `none`이며, 볼륨에 대해 스냅샷이 자동으로 생성되지 않음을 의미합니다. 스토리지 관리자가 수정하지 않는 한, 모든 ONTAP 시스템에는 "default"라는 정책이 존재하며, 이 정책은 6개의 시간별, 2개의 일별, 2개의 주별 스냅샷을 생성하고 보존합니다. 스냅샷에 보존된 데이터는 볼륨 내 모든 디렉터리의 `.snapshot` 디렉터리를 탐색하여 복구할 수 있습니다.



| `snapshotReserve`  a| 
이렇게 하면 스냅샷 예약 공간이 원하는 비율로 설정됩니다. 기본값은 값이 없음을 의미하며, snapshotPolicy를 선택한 경우 ONTAP가 snapshotReserve(일반적으로 5%)를 선택하고, snapshotPolicy가 none인 경우 0%를 선택합니다. 모든 ONTAP 백엔드에 대해 구성 파일에서 기본 snapshotReserve 값을 설정할 수 있으며, ontap-nas-economy를 제외한 모든 ONTAP 백엔드의 볼륨 생성 옵션으로 사용할 수 있습니다.



| `splitOnClone`  a| 
볼륨을 복제할 때 이 옵션을 선택하면 ONTAP가 복제본을 상위 볼륨에서 즉시 분할합니다. 기본값은 `false`입니다. 볼륨 복제를 위한 일부 사용 사례는 스토리지 효율성을 위한 기회가 거의 없기 때문에 생성 즉시 복제본을 상위 볼륨에서 분할하는 것이 가장 좋습니다. 예를 들어, 빈 데이터베이스를 복제하면 시간은 크게 절약할 수 있지만 스토리지 절약 효과는 거의 없으므로 복제본을 즉시 분할하는 것이 가장 좋습니다.



| `encryption`  a| 
새 볼륨에서 NetApp Volume Encryption(NVE)을 활성화합니다. 기본값은 `false`입니다. 이 옵션을 사용하려면 클러스터에서 NVE 라이센스가 있고 활성화되어 있어야 합니다.

백엔드에서 NAE가 활성화된 경우 Trident에서 프로비저닝된 모든 볼륨에 NAE가 활성화됩니다.

자세한 내용은 link:../trident-reco/security-reco.html["Trident가 NVE 및 NAE와 작동하는 방식"]을(를) 참조하십시오.



| `tieringPolicy`  a| 
볼륨에 사용할 티어링 정책을 설정합니다. 이 정책은 데이터가 비활성화(콜드)될 때 클라우드 티어로 이동할지 여부를 결정합니다.

|===
다음 추가 옵션은 NFS *전용*입니다.

[cols="2*"]
|===
| 옵션 | 설명 


| `unixPermissions`  a| 
이 설정은 볼륨 자체에 대한 권한 설정을 제어합니다. 기본적으로 권한은  ``---rwxr-xr-x` 또는 숫자 표기법으로 0755로 설정되며,  `root`가 소유자입니다. 텍스트 또는 숫자 형식 모두 사용 가능합니다.



| `snapshotDir`  a| 
이 값을 `true`로 설정하면 `.snapshot` 디렉터리가 볼륨에 액세스하는 클라이언트에 표시됩니다. 기본값은 `false`이며, 이는 `.snapshot` 디렉터리의 가시성이 기본적으로 비활성화되어 있음을 의미합니다. 일부 이미지(예: 공식 MySQL 이미지)는 `.snapshot` 디렉터리가 표시될 때 예상대로 작동하지 않습니다.



| `exportPolicy`  a| 
볼륨에 사용할 내보내기 정책을 설정합니다. 기본값은 `default`입니다.



| `securityStyle`  a| 
볼륨 접근에 사용할 보안 스타일을 설정합니다. 기본값은 `unix`입니다. 유효한 값은 `unix` 및 `mixed`입니다.

|===
다음 추가 옵션은 iSCSI *전용*입니다.

[cols="2*"]
|===
| 옵션 | 설명 


| `fileSystemType` | iSCSI 볼륨 포맷에 사용되는 파일 시스템을 설정합니다. 기본값은 `ext4`입니다. 유효한 값은 `ext3`, `ext4` 및 `xfs`입니다. 


| `spaceAllocation` | 이 값을 `false`로 설정하면 LUN의 공간 할당 기능이 비활성화됩니다. 기본값은 `true`이며, ONTAP이 볼륨의 공간이 부족해져 해당 볼륨의 LUN에서 쓰기 작업을 더 이상 수행할 수 없을 때 호스트에 알림을 보낸다는 의미입니다. 또한 이 옵션을 사용하면 호스트에서 데이터를 삭제할 때 ONTAP이 자동으로 공간을 회수할 수 있습니다. 
|===


=== 예

아래 예를 참조하십시오.

* 10 GiB 볼륨을 생성합니다.
+
[listing]
----
docker volume create -d netapp --name demo -o size=10G -o encryption=true
----
* 스냅샷이 있는 100GiB 볼륨 생성:
+
[listing]
----
docker volume create -d netapp --name demo -o size=100G -o snapshotPolicy=default -o snapshotReserve=10
----
* setUID 비트가 활성화된 볼륨을 생성합니다.
+
[listing]
----
docker volume create -d netapp --name demo -o unixPermissions=4755
----


최소 볼륨 크기는 20MiB입니다.

스냅샷 예약량이 지정되지 않고 스냅샷 정책이 `none`인 경우 Trident는 0%의 스냅샷 예약량을 사용합니다.

* 스냅샷 정책 및 스냅샷 예약이 없는 볼륨을 생성합니다.
+
[listing]
----
docker volume create -d netapp --name my_vol --opt snapshotPolicy=none
----
* 스냅샷 정책이 없고 사용자 지정 스냅샷 예약률이 10%인 볼륨을 생성합니다.
+
[listing]
----
docker volume create -d netapp --name my_vol --opt snapshotPolicy=none --opt snapshotReserve=10
----
* 스냅샷 정책과 10%의 사용자 지정 스냅샷 예약 공간을 사용하여 볼륨을 생성합니다.
+
[listing]
----
docker volume create -d netapp --name my_vol --opt snapshotPolicy=myPolicy --opt snapshotReserve=10
----
* 스냅샷 정책이 적용된 볼륨을 생성하고 ONTAP의 기본 스냅샷 예약값(일반적으로 5%)을 수락하십시오.
+
[listing]
----
docker volume create -d netapp --name my_vol --opt snapshotPolicy=myPolicy
----




== Element 소프트웨어 볼륨 옵션

Element 소프트웨어 옵션은 볼륨과 관련된 크기 및 서비스 품질(QoS) 정책을 표시합니다. 볼륨을 생성할 때 해당 볼륨과 연결된 QoS 정책은  `-o type=service_level` 명명법을 사용하여 지정됩니다.

Element 드라이버를 사용하여 QoS 서비스 수준을 정의하는 첫 번째 단계는 하나 이상의 유형을 생성하고 구성 파일에서 이름과 연결된 최소, 최대 및 버스트 IOPS를 지정하는 것입니다.

기타 Element 소프트웨어 볼륨 생성 옵션은 다음과 같습니다.

[cols="2*"]
|===
| 옵션 | 설명 


| `size`  a| 
볼륨의 크기는 기본값으로 1GiB 또는 구성 항목 ... "기본값": {"size": "5G"}.



| `blocksize`  a| 
512 또는 4096 중 하나를 사용하십시오. 기본값은 512 또는 구성 항목 DefaultBlockSize입니다.

|===


=== 예

다음은 QoS 정의가 포함된 샘플 구성 파일입니다.

[source, json]
----
{
  "Types": [
    {
      "Type": "Bronze",
      "Qos": {
        "minIOPS": 1000,
        "maxIOPS": 2000,
        "burstIOPS": 4000
      }
    },
    {
      "Type": "Silver",
      "Qos": {
        "minIOPS": 4000,
        "maxIOPS": 6000,
        "burstIOPS": 8000
      }
    },
    {
      "Type": "Gold",
      "Qos": {
        "minIOPS": 6000,
        "maxIOPS": 8000,
        "burstIOPS": 10000
      }
    }
  ]
}
----
위 구성에는 Bronze, Silver, Gold라는 세 가지 정책 정의가 있습니다. 이 이름은 임의로 지정한 것입니다.

* 10GiB Gold 볼륨을 생성합니다.
+
[listing]
----
docker volume create -d solidfire --name sfGold -o type=Gold -o size=10G
----
* 100 GiB Bronze 볼륨 생성:
+
[listing]
----
docker volume create -d solidfire --name sfBronze -o type=Bronze -o size=100G
----

