---
sidebar: sidebar 
permalink: trident-docker/volumes-docker.html 
keywords: create volumes, Trident, trident for docker, docker, docker volume 
summary: '볼륨을 생성하려면 필요에 따라 Trident 드라이버 이름을 지정하여 표준 `docker volume` 명령을 사용하십시오.' 
---
= 볼륨 작업
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
필요에 따라 Trident 드라이버 이름을 지정하여 표준 `docker volume` 명령을 사용하면 볼륨을 쉽게 생성, 복제 및 제거할 수 있습니다.



== 볼륨 생성

* 기본 이름을 사용하여 드라이버로 볼륨 생성:
+
[source, console]
----
docker volume create -d netapp --name firstVolume
----
* 특정 Trident 인스턴스를 사용하여 볼륨 생성:
+
[source, console]
----
docker volume create -d ntap_bronze --name bronzeVolume
----
+

NOTE: link:volume-driver-options.html["옵션"^]을 지정하지 않으면 드라이버의 기본값이 사용됩니다.

* 기본 볼륨 크기를 재정의합니다. 드라이버를 사용하여 20GiB 볼륨을 생성하는 방법은 다음 예제를 참조하십시오.
+
[source, console]
----
docker volume create -d netapp --name my_vol --opt size=20G
----
+

TIP: 볼륨 크기는 정수 값과 선택적으로 단위를 포함하는 문자열로 표현됩니다(예: 10G, 20GB, 3TiB). 단위가 지정되지 않은 경우 기본값은 G입니다. 크기 단위는 2의 거듭제곱(B, KiB, MiB, GiB, TiB) 또는 10의 거듭제곱(B, KB, MB, GB, TB)으로 표현할 수 있습니다. 간략한 단위 표기에는 2의 거듭제곱이 사용됩니다(G = GiB, T = TiB 등).





== 볼륨 제거

* 다른 Docker 볼륨과 마찬가지로 볼륨을 제거하십시오:
+
[source, console]
----
docker volume rm firstVolume
----
+

IMPORTANT:  `solidfire-san` 드라이버를 사용할 때 위의 예에서는 볼륨을 삭제하고 제거합니다.



Docker용 Trident를 업그레이드하려면 아래 단계를 수행하십시오.



== 볼륨 복제

 `ontap-nas`,  `ontap-san` 및  `solidfire-san` 스토리지 드라이버를 사용하는 경우 Trident는 볼륨을 복제할 수 있습니다.  `ontap-nas-flexgroup` 또는  `ontap-nas-economy` 드라이버를 사용하는 경우에는 복제가 지원되지 않습니다. 기존 볼륨에서 새 볼륨을 생성하면 새 스냅샷이 생성됩니다.

* 볼륨을 검사하여 스냅샷을 열거합니다.
+
[source, console]
----
docker volume inspect <volume_name>
----
* 기존 볼륨에서 새 볼륨을 생성합니다. 이렇게 하면 새 스냅샷이 생성됩니다.
+
[source, console]
----
docker volume create -d <driver_name> --name <new_name> -o from=<source_docker_volume>
----
* 볼륨의 기존 스냅샷에서 새 볼륨을 생성합니다. 새 스냅샷이 생성되지 않습니다.
+
[source, console]
----
docker volume create -d <driver_name> --name <new_name> -o from=<source_docker_volume> -o fromSnapshot=<source_snap_name>
----




=== 예

[source, console]
----
docker volume inspect firstVolume

[
  {
    "Driver": "ontap-nas",
    "Labels": null,
    "Mountpoint": "/var/lib/docker-volumes/ontap-nas/netappdvp_firstVolume",
    "Name": "firstVolume",
    "Options": {},
    "Scope": "global",
    "Status": {
      "Snapshots": [
        {
          "Created": "2017-02-10T19:05:00Z",
          "Name": "hourly.2017-02-10_1505"
        }
      ]
    }
  }
]

docker volume create -d ontap-nas --name clonedVolume -o from=firstVolume
clonedVolume

docker volume rm clonedVolume
docker volume create -d ontap-nas --name volFromSnap -o from=firstVolume -o fromSnapshot=hourly.2017-02-10_1505
volFromSnap

docker volume rm volFromSnap
----


== 외부에서 생성된 볼륨에 액세스

컨테이너는 Trident를 사용하여 외부에서 생성된 블록 디바이스(또는 해당 클론)에 액세스할 수 있습니다. *단*, 해당 디바이스에 파티션이 없고 파일 시스템이 Trident에서 지원되는 경우에만 가능합니다(예:  `ext4`로 포맷된 `/dev/sdc1` 디바이스는 Trident를 통해 액세스할 수 없음).
