---
sidebar: sidebar 
permalink: get-help.html 
keywords: get help, get support, knowledgebase, discord, phone, web, ticket, contact support, support ticket 
summary: NetApp은 다양한 방식으로 Trident를 지원합니다. Discord 채널과 같은 광범위한 무료 자가 지원 옵션을 연중무휴 24시간 이용할 수 있습니다. 
---
= 지원
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp은 다양한 방식으로 Trident를 지원합니다. 기술 자료(KB) 문서 및 Discord 채널과 같은 광범위한 무료 자가 지원 옵션을 연중무휴 24시간 이용할 수 있습니다.



== Trident 지원 라이프사이클

Trident는 버전에 따라 세 가지 수준의 지원을 제공합니다. link:https://mysupport.netapp.com/site/info/version-support["NetApp 소프트웨어 버전 정의 지원"^]을 참조하십시오.

완전 지원:: Trident는 출시일로부터 12개월 동안 완벽한 지원을 제공합니다.
제한적 지원:: Trident는 출시일로부터 13개월에서 24개월 동안 제한적인 지원을 제공합니다.
자가 지원:: Trident 문서는 출시일로부터 25~36개월 동안 제공됩니다.


[cols="1, 1, 1, 1"]
|===


| 버전 | 완전 지원 | 제한적 지원 | 자가 지원 


 a| 
link:https://docs.netapp.com/us-en/trident-2510/index.html["25.10"^]
| 2026년 10월 | 2027년 10월 | 2028년 10월 


 a| 
link:https://docs.netapp.com/us-en/trident-2506/index.html["25.06"^]
| 2026년 6월 | 2027년 6월 | 2028년 6월 


 a| 
link:https://docs.netapp.com/us-en/trident-2502/index.html["25.02"^]
| 2026년 2월 | 2027년 2월 | 2028년 2월 


 a| 
link:https://docs.netapp.com/us-en/trident-2410/index.html["24.10"^]
| -- | 2026년 10월 | 2027년 10월 


 a| 
link:https://docs.netapp.com/us-en/trident-2406/index.html["24.06"^]
| -- | 2026년 6월 | 2027년 6월 


 a| 
link:https://docs.netapp.com/us-en/trident-2402/index.html["24.02"^]
| -- | 2026년 2월 | 2027년 2월 


 a| 
link:https://docs.netapp.com/us-en/trident-2310/index.html["23.10"^]
| -- | -- | 2026년 10월 


 a| 
link:https://docs.netapp.com/us-en/trident-2307/index.html["23.07"^]
| -- | -- | 2026년 7월 


 a| 
link:https://docs.netapp.com/us-en/trident-2304/index.html["23.04"^]
| -- | -- | 2026년 4월 


 a| 
link:https://docs.netapp.com/us-en/trident-2301/index.html["23.01"^]
| -- | -- | 2026년 1월 
|===

NOTE: 최신 Trident 버전 지원 일정은 https://docs.netapp.com/us-en/trident/get-help.html#trident-support-lifecycle["지원 수명 주기 페이지"]을 참조하십시오.



== 자가 지원

문제 해결 관련 문서의 전체 목록을 보려면 https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Trident_Kubernetes["NetApp 기술 자료(로그인 필요)"^]을 참조하십시오.



== 커뮤니티 지원

저희 link:https://discord.gg/NetApp["Discord 채널"^]에는 컨테이너 사용자(Trident 개발자 포함)들의 활발한 공개 커뮤니티가 있습니다. 이곳은 프로젝트에 대한 일반적인 질문을 하고 비슷한 생각을 가진 동료들과 관련 주제에 대해 토론하기에 좋은 곳입니다.



== NetApp 기술 지원

Trident에 대한 도움이 필요하면 `tridentctl logs -a -n trident`을 사용하여 지원 번들을 생성하고 `NetApp Support <Getting Help>`로 보내십시오.



== 자세한 내용은

* link:https://github.com/NetApp/trident["Trident 리소스"^]
* link:https://cloud.netapp.com/kubernetes-hub["Kubernetes Hub"^]

