---
sidebar: sidebar 
permalink: trident-use/anf.html 
keywords: trident backend, azure netapp files, smb volumes, smb, windows, drivers, access modes, rwo, rwx, rwp, rwop, file system, aks, managed identities, azure 
summary: 'Azure NetApp Files를 Trident의 백엔드로 구성할 수 있습니다. Azure NetApp Files 백엔드를 사용하여 NFS 및 SMB 볼륨을 연결할 수 있습니다. Trident는 Azure Kubernetes Services(AKS) 클러스터용 관리 ID를 사용한 자격 증명 관리를 지원합니다.' 
---
= Azure NetApp Files 백엔드 구성
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Azure NetApp Files를 Trident의 백엔드로 구성할 수 있습니다. Azure NetApp Files 백엔드를 사용하여 NFS 및 SMB 볼륨을 연결할 수 있습니다. Trident는 Azure Kubernetes Services(AKS) 클러스터용 관리 ID를 사용한 자격 증명 관리를 지원합니다.



== Azure NetApp Files 드라이버 세부 정보

Trident는 클러스터와의 통신을 위해 다음과 같은 Azure NetApp Files 스토리지 드라이버를 제공합니다. 지원되는 액세스 모드는 _ReadWriteOnce_(RWO), _ReadOnlyMany_(ROX), _ReadWriteMany_(RWX), _ReadWriteOncePod_(RWOP)입니다.

[cols="2, 1, 1, 2, 2"]
|===
| 드라이버 | 프로토콜 | volumeMode | 지원되는 액세스 모드 | 지원되는 파일 시스템 


| `azure-netapp-files`  a| 
NFS SMB
 a| 
파일 시스템
 a| 
RWO, ROX, RWX, RWOP
 a| 
`nfs`, `smb`

|===


=== 고려 사항

* Azure NetApp Files 서비스는 50GiB보다 작은 볼륨을 지원하지 않습니다. 더 작은 볼륨이 요청될 경우 Trident는 자동으로 50GiB 볼륨을 생성합니다.
* Trident는 Windows 노드에서 실행되는 Pod에 마운트된 SMB 볼륨만 지원합니다.




== AKS용 관리 ID

Trident는 Azure Kubernetes Services 클러스터에 대한 link:https://learn.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview["관리 ID"^]를 지원합니다. 관리형 ID에서 제공하는 간소화된 자격 증명 관리 기능을 활용하려면 다음이 필요합니다.

* AKS를 사용하여 배포된 Kubernetes 클러스터
* AKS Kubernetes 클러스터에 구성된 관리 ID
* Trident가 설치되어 있으며  `cloudProvider`를 지정하기 위한  `"Azure"`가 포함되어 있습니다.
+
[role="tabbed-block"]
====
.Trident 운영자
--
Trident 운영자를 사용하여 Trident를 설치하려면 `tridentorchestrator_cr.yaml`을 편집하여 `cloudProvider`를 `"Azure"`로 설정하십시오. 예를 들면 다음과 같습니다.

[source, yaml]
----
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  imagePullPolicy: IfNotPresent
  cloudProvider: "Azure"
----
--
.Helm
--
다음 예시는 환경 변수 `$CP`를 사용하여 Trident sets `cloudProvider`를 Azure에 설치합니다:

[listing]
----
helm install trident trident-operator-100.2506.0.tgz --create-namespace --namespace <trident-namespace> --set cloudProvider=$CP
----
--
.<code>tridentctl</code>
--
다음 예제는 Trident를 설치하고 `cloudProvider` 플래그를 `Azure`로 설정합니다:

[listing]
----
tridentctl install --cloud-provider="Azure" -n trident
----
--
====




== AKS용 클라우드 ID

클라우드 ID를 사용하면 Kubernetes Pod가 명시적인 Azure 자격 증명을 제공하는 대신 워크로드 ID로 인증하여 Azure 리소스에 액세스할 수 있습니다.

Azure에서 클라우드 ID를 활용하려면 다음이 필요합니다.

* AKS를 사용하여 배포된 Kubernetes 클러스터
* AKS Kubernetes 클러스터에 구성된 워크로드 ID 및 oidc-issuer
*  `cloudProvider`을(를) 지정하고  `"Azure"` 및  `cloudIdentity`을(를) 지정하여 워크로드 ID를 지정하는 기능이 포함된 Trident가 설치되어 있습니다
+
[role="tabbed-block"]
====
.Trident 운영자
--
Trident 운영자를 사용하여 Trident를 설치하려면 `tridentorchestrator_cr.yaml`을 편집하여 `cloudProvider`를 `"Azure"`로 설정하고 `cloudIdentity`를 `azure.workload.identity/client-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx`로 설정하십시오.

예를 들면 다음과 같습니다.

[source, yaml]
----
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  imagePullPolicy: IfNotPresent
  cloudProvider: "Azure"
  cloudIdentity: 'azure.workload.identity/client-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx' # Edit
----
--
.Helm
--
다음 환경 변수를 사용하여 *cloud-provider(CP)* 및 *cloud-identity(CI)* 플래그 값을 설정하십시오.

`export CP="Azure"`
`export CI="'azure.workload.identity/client-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx'"`

다음 예제는 Trident를 설치하고 `cloudProvider`를 환경 변수 `$CP`를 사용하여 Azure로 설정하며 `cloudIdentity`를 환경 변수 `$CI`를 사용하여 설정합니다:

[listing]
----
helm install trident trident-operator-100.6.0.tgz --set cloudProvider=$CP --set cloudIdentity="$CI"
----
--
.<code>tridentctl</code>
--
다음 환경 변수를 사용하여 *cloud provider* 및 *cloud identity* 플래그 값을 설정하십시오.

`export CP="Azure"`
`export CI="azure.workload.identity/client-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx"`

다음 예제는 Trident를 설치하고 `cloud-provider` 플래그를 `$CP`로, 그리고 `cloud-identity`를 `$CI`로 설정합니다:

[listing]
----
tridentctl install --cloud-provider=$CP --cloud-identity="$CI" -n trident
----
--
====

