---
sidebar: sidebar 
permalink: trident-use/backend_ops_tridentctl.html 
keywords: backends, storage system, anf, element, hci, solidfire, ontap, aff, fas, ontap select, configure backends, tridentctl, create backends, delete backends, view backends, update backends 
summary: ' `tridentctl`를 사용하여 백엔드 관리 작업을 수행하는 방법에 대해 알아보십시오.' 
---
= tridentctl을 사용하여 백엔드 관리를 수행합니다
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
 `tridentctl`를 사용하여 백엔드 관리 작업을 수행하는 방법에 대해 알아보십시오.



== 백엔드 생성

link:backends.html["백엔드 구성 파일"^]를 생성한 후 다음 명령을 실행하십시오.

[listing]
----
tridentctl create backend -f <backend-file> -n trident
----
백엔드 생성에 실패하면 백엔드 구성에 문제가 있는 것입니다. 다음 명령을 실행하여 로그를 보고 원인을 확인할 수 있습니다.

[listing]
----
tridentctl logs -n trident
----
구성 파일의 문제를 식별하고 수정한 후  `create` 명령을 다시 실행하기만 하면 됩니다.



== 백엔드를 삭제합니다

Trident에서 백엔드를 삭제하려면 다음 단계를 따르세요.

. 백엔드 이름 검색:
+
[listing]
----
tridentctl get backend -n trident
----
. 백엔드 삭제:
+
[listing]
----
tridentctl delete backend <backend-name> -n trident
----



NOTE: Trident가 이 백엔드에서 프로비저닝한 볼륨과 스냅샷이 아직 남아 있는 경우, 백엔드를 삭제하면 해당 백엔드에서 새 볼륨을 프로비저닝할 수 없습니다. 백엔드는 "Deleting" 상태로 계속 유지됩니다.



== 기존 백엔드 보기

Trident가 알고 있는 백엔드를 보려면 다음을 수행합니다.

* 요약을 보려면 다음 명령을 실행하십시오.
+
[listing]
----
tridentctl get backend -n trident
----
* 모든 세부 정보를 확인하려면 다음 명령을 실행하십시오.
+
[listing]
----
tridentctl get backend -o json -n trident
----




== 백엔드 업데이트

새 백엔드 구성 파일을 생성한 후 다음 명령을 실행하십시오.

[listing]
----
tridentctl update backend <backend-name> -f <backend-file> -n trident
----
백엔드 업데이트가 실패하면 백엔드 구성에 문제가 있거나 유효하지 않은 업데이트를 시도한 것입니다. 다음 명령을 실행하여 로그를 확인하고 원인을 파악할 수 있습니다.

[listing]
----
tridentctl logs -n trident
----
구성 파일의 문제를 식별하고 수정한 후  `update` 명령을 다시 실행하기만 하면 됩니다.



== 백엔드를 사용하는 스토리지 클래스를 식별합니다

이는 백엔드 객체에 대해  `tridentctl`이(가) 출력하는 JSON을 사용하여 답변할 수 있는 질문 유형의 예입니다. 이는 설치해야 하는  `jq` 유틸리티를 사용합니다.

[listing]
----
tridentctl get backend -o json | jq '[.items[] | {backend: .name, storageClasses: [.storage[].storageClasses]|unique}]'
----
이는 `TridentBackendConfig`을 사용하여 생성된 백엔드에도 적용됩니다.
