---
sidebar: sidebar 
permalink: trident-use/manage-stor-class.html 
keywords: storage class, manage storage class, storage classes, kubernetes storage classes 
summary: 기존 스토리지 클래스를 보고, 기본 스토리지 클래스를 설정하고, 스토리지 클래스 백엔드를 식별하고, 스토리지 클래스를 삭제할 수 있습니다. 
---
= 스토리지 클래스 관리
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
기존 스토리지 클래스를 보고, 기본 스토리지 클래스를 설정하고, 스토리지 클래스 백엔드를 식별하고, 스토리지 클래스를 삭제할 수 있습니다.



== 기존 스토리지 클래스를 확인합니다

* 기존 Kubernetes 스토리지 클래스를 보려면 다음 명령을 실행하십시오.


[listing]
----
kubectl get storageclass
----
* Kubernetes 스토리지 클래스 세부 정보를 보려면 다음 명령을 실행하십시오.


[listing]
----
kubectl get storageclass <storage-class> -o json
----
* Trident의 동기화된 스토리지 클래스를 보려면 다음 명령을 실행하십시오.


[listing]
----
tridentctl get storageclass
----
* Trident의 동기화된 스토리지 클래스 세부 정보를 보려면 다음 명령을 실행하십시오.


[listing]
----
tridentctl get storageclass <storage-class> -o json
----


== 기본 스토리지 클래스를 설정합니다

Kubernetes 1.6에서는 기본 스토리지 클래스를 설정하는 기능이 추가되었습니다. 사용자가 영구 볼륨 클레임(PVC)에서 스토리지 클래스를 지정하지 않으면 이 기본 스토리지 클래스가 영구 볼륨을 프로비저닝하는 데 사용됩니다.

* 스토리지 클래스 정의에서 주석 `storageclass.kubernetes.io/is-default-class`을 true로 설정하여 기본 스토리지 클래스를 정의합니다. 사양에 따르면 다른 값이나 주석이 없으면 false로 해석됩니다.
* 다음 명령을 사용하여 기존 스토리지 클래스를 기본 스토리지 클래스로 구성할 수 있습니다.


[listing]
----
kubectl patch storageclass <storage-class-name> -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
----
* 마찬가지로 다음 명령을 사용하여 기본 스토리지 클래스 주석을 제거할 수 있습니다.


[listing]
----
kubectl patch storageclass <storage-class-name> -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'
----
Trident 설치 프로그램 번들에도 이 주석이 포함된 예제가 있습니다.


NOTE: 클러스터에는 한 번에 하나의 기본 스토리지 클래스만 있어야 합니다. Kubernetes는 기술적으로 두 개 이상의 스토리지 클래스를 사용하는 것을 막지는 않지만 기본 스토리지 클래스가 전혀 없는 것처럼 작동합니다.



== 스토리지 클래스의 백엔드를 식별합니다

이는  `tridentctl` Trident 백엔드 객체에 대해 출력되는 JSON을 사용하여 답변할 수 있는 질문 유형의 예입니다. 이 예시에서는  `jq` 유틸리티를 사용하는데, 필요에 따라 먼저 설치해야 할 수도 있습니다.

[listing]
----
tridentctl get storageclass -o json | jq  '[.items[] | {storageClass: .Config.name, backends: [.storage]|unique}]'
----


== 스토리지 클래스를 삭제합니다

Kubernetes에서 스토리지 클래스를 삭제하려면 다음 명령을 실행하십시오.

[listing]
----
kubectl delete storageclass <storage-class>
----
`<storage-class>`는 스토리지 클래스로 교체해야 합니다.

이 스토리지 클래스를 통해 생성된 영구 볼륨은 변경되지 않고 그대로 유지되며, Trident가 계속해서 해당 볼륨을 관리합니다.


NOTE: Trident는 생성하는 볼륨에 대해 빈 `fsType`을 적용합니다. iSCSI 백엔드의 경우 StorageClass에서 `parameters.fsType`을 적용하는 것이 좋습니다. 기존 StorageClasses를 삭제하고 `parameters.fsType`이 지정된 상태로 다시 생성해야 합니다.
