---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-deploy-tridentctl.html 
keywords: deploy, Trident, methods, tridentctl, windows 
summary: ' `tridentctl`를 사용하여 Trident를 설치할 수 있습니다. 이 프로세스는 Trident에 필요한 컨테이너 이미지가 개인 레지스트리에 저장되어 있는지 여부와 관계없이 설치에 적용됩니다.' 
---
= tridentctl을 사용하여 설치
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
 `tridentctl`를 사용하여 Trident를 설치할 수 있습니다. 이 프로세스는 Trident에 필요한 컨테이너 이미지가 개인 레지스트리에 저장되어 있거나 저장되어 있지 않은 설치에 적용됩니다.  `tridentctl` 배포를 사용자 지정하려면 link:kubernetes-customize-deploy-tridentctl.html["tridentctl 배포 사용자 지정"]를 참조하십시오.



== Trident10에 대한 중요 정보

*Trident에 대한 다음 중요 정보를 읽어야 합니다.*

.<strong>Trident에 대한 중요 정보</strong>
[%collapsible%open]
====
* 이제 Kubernetes 1.27이 Trident에서 지원됩니다. Kubernetes를 업그레이드하기 전에 Trident를 업그레이드하십시오.
* Trident는 SAN 환경에서 다중 경로 구성 사용을 엄격하게 시행하며, multipath.conf 파일에 권장 값은  `find_multipaths: no`입니다.
+
다중 경로를 사용하지 않는 구성 또는 multipath.conf 파일에서 `find_multipaths: yes` 또는 `find_multipaths: smart` 값을 사용하면 마운트가 실패합니다. Trident는 21.07 릴리스부터 `find_multipaths: no` 사용을 권장해 왔습니다.



====


==  `tridentctl`를 사용하여 Trident 설치

link:../trident-get-started/kubernetes-deploy.html["설치 개요"]을(를) 검토하여 설치 사전 요구 사항을 충족했는지, 그리고 사용 환경에 맞는 올바른 설치 옵션을 선택했는지 확인하십시오.

.시작하기 전에
설치를 시작하기 전에 Linux 호스트에 로그인하여 작동 중인 link:requirements.html["지원되는 Kubernetes 클러스터"^]를 관리하고 있는지, 필요한 권한이 있는지 확인합니다.


NOTE: OpenShift를 사용할 때, 아래 모든 예제에서  `oc`을(를)  `kubectl` 대신 사용하고, 먼저  `oc login -u system:admin` 또는  `oc login -u kube-admin`을(를) 실행하여 *system:admin*으로 로그인하십시오.

[%collapsible%open]
====
. Kubernetes 버전을 확인합니다.
+
[listing]
----
kubectl version
----
. 클러스터 관리자 권한을 확인하십시오.
+
[listing]
----
kubectl auth can-i '*' '*' --all-namespaces
----
. Docker Hub의 이미지를 사용하는 Pod를 시작하고 Pod 네트워크를 통해 스토리지 시스템에 연결할 수 있는지 확인하십시오.
+
[listing]
----
kubectl run -i --tty ping --image=busybox --restart=Never --rm -- \
  ping <management IP>
----


====


== 1단계: Trident 설치 패키지를 다운로드하세요.

Trident 설치 프로그램 패키지는 Trident Pod를 생성하고, 상태를 유지하는 데 사용되는 CRD 객체를 구성하며, 클러스터 호스트에 볼륨을 프로비저닝하고 연결하는 등의 작업을 수행하도록 CSI 사이드카를 초기화합니다. link:https://github.com/NetApp/trident/releases/latest["GitHub의 _Assets_ 섹션"^]에서 최신 버전의 Trident 설치 프로그램을 다운로드하여 압축을 풉니다. 예제의 _<trident-installer-XX.XX.X.tar.gz>_를 선택한 Trident 버전으로 업데이트합니다.

[listing]
----
wget https://github.com/NetApp/trident/releases/download/v25.10.0/trident-installer-25.10.0.tar.gz
tar -xf trident-installer-25.10.0.tar.gz
cd trident-installer
----


== 2단계: Trident 설치

 `tridentctl install` 명령을 실행하여 원하는 네임스페이스에 Trident를 설치합니다. 추가 인수를 추가하여 이미지 레지스트리 위치를 지정할 수 있습니다.

[role="tabbed-block"]
====
.표준 모드
--
[listing]
----
./tridentctl install -n trident
----
--
.하나의 레지스트리에 있는 이미지
--
[listing]
----
./tridentctl install -n trident --image-registry <your-registry> --autosupport-image <your-registry>/trident-autosupport:25.10 --trident-image <your-registry>/trident:25.10.0
----
--
.서로 다른 레지스트리에 있는 이미지
--
[listing]
----
./tridentctl install -n trident --image-registry <your-registry> --autosupport-image <your-registry>/trident-autosupport:25.10 --trident-image <your-registry>/trident:25.10.0
----
--
====
설치 상태는 다음과 같이 표시되어야 합니다.

[listing]
----
....
INFO Starting Trident installation.                namespace=trident
INFO Created service account.
INFO Created cluster role.
INFO Created cluster role binding.
INFO Added finalizers to custom resource definitions.
INFO Created Trident service.
INFO Created Trident secret.
INFO Created Trident deployment.
INFO Created Trident daemonset.
INFO Waiting for Trident pod to start.
INFO Trident pod started.                          namespace=trident pod=trident-controller-679648bd45-cv2mx
INFO Waiting for Trident REST interface.
INFO Trident REST interface is up.                 version=25.10.0
INFO Trident installation succeeded.
....
----


== 설치 확인

파드 생성 상태 또는 `tridentctl`를 사용하여 설치를 확인할 수 있습니다.



=== POD 생성 상태 사용

생성된 Pod의 상태를 검토하여 Trident 설치가 완료되었는지 확인할 수 있습니다.

[listing]
----
kubectl get pods -n trident

NAME                                  READY   STATUS    RESTARTS   AGE
trident-controller-679648bd45-cv2mx   6/6     Running   0          5m29s
trident-node-linux-vgc8n              2/2     Running   0          5m29s
----

NOTE: 설치 프로그램이 성공적으로 완료되지 않거나 `trident-controller-<generated id>` (`trident-csi-<generated id>`에 *실행 중* 상태가 표시되지 않으면 플랫폼이 설치되지 않은 것입니다.  `-d`를 사용하여 link:../troubleshooting.html#troubleshooting-an-unsuccessful-trident-deployment-using-tridentctl["디버그 모드 켜기"]하고 문제를 해결하세요.



=== 사용 `tridentctl`

 `tridentctl` 을 사용하여 설치된 Trident 버전을 확인할 수 있습니다.

[listing]
----
./tridentctl -n trident version

+----------------+----------------+
| SERVER VERSION | CLIENT VERSION |
+----------------+----------------+
| 25.10.0        | 25.10.0        |
+----------------+----------------+
----


== 샘플 구성

다음 예는 `tridentctl`을 사용하여 Trident를 설치하는 샘플 구성을 제공합니다.

.Windows 노드
[%collapsible]
====
Windows 노드에서 Trident를 실행하려면 다음을 수행합니다.

[listing]
----
tridentctl install --windows -n trident
----
====
.강제 분리
[%collapsible]
====
자세한 내용은 link:../trident-reco/force-detach.html["Trident를 사용하여 상태 저장 애플리케이션의 페일오버 자동화"]을 참조하십시오.

[listing]
----
tridentctl install --enable-force-detach=true -n trident
----
====
.동시 Trident 컨트롤러 작업 활성화
[%collapsible]
====
처리량 향상을 위해 동시 Trident 컨트롤러 작업을 활성화하려면 이 예에 표시된 대로 설치 중에  `--enable-concurrency` 옵션을 추가하십시오.


NOTE: *Tech Preview*: 이 기능은 실험적이며 현재 ONTAP-NAS(NFS만 해당) 및 ONTAP-SAN(통합 ONTAP 9용 NVMe) 드라이버를 사용한 제한된 병렬 워크플로를 지원하며, ONTAP-SAN 드라이버(통합 ONTAP 9의 iSCSI 및 FCP 프로토콜)에 대한 기존 Tech Preview도 지원합니다.

[listing]
----
tridentctl install --enable-concurrency -n trident
----
====