---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-deploy-helm-mirror.html 
keywords: deploy, Trident, operator, helm, helm chart, configuration, values, offline, air gap, gap, registry 
summary: Helm을 사용하여 Trident 오퍼레이터를 배포하고 Trident를 설치할 수 있습니다. 이 프로세스는 Trident에 필요한 컨테이너 이미지가 프라이빗 레지스트리에 저장된 설치 환경에 적용됩니다. 
---
= Helm을 사용하여 Trident 운영자 배포(오프라인 모드)
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Helm을 사용하여 Trident 오퍼레이터를 배포하고 Trident를 설치할 수 있습니다. 이 프로세스는 Trident에 필요한 컨테이너 이미지가 프라이빗 레지스트리에 저장된 설치에 적용됩니다. 프라이빗 이미지 레지스트리가 없는 경우 link:kubernetes-deploy-helm.html["표준 배포 프로세스"]을 사용하십시오.



== Trident 25.10에 대한 중요 정보

*Trident에 대한 다음 중요 정보를 읽어야 합니다.*

.<strong>Trident에 대한 중요 정보</strong>
[%collapsible%open]
====
[]
=====
* Kubernetes 1.34는 이제 Trident에서 지원됩니다. Kubernetes를 업그레이드하기 전에 Trident를 먼저 업그레이드하십시오.
* Trident는 SAN 환경에서 다중 경로 구성 사용을 엄격하게 시행하며, multipath.conf 파일에 권장 값은  `find_multipaths: no`입니다.
+
다중 경로를 사용하지 않는 구성 또는 multipath.conf 파일에서 `find_multipaths: yes` 또는 `find_multipaths: smart` 값을 사용하면 마운트가 실패합니다. Trident는 21.07 릴리스부터 `find_multipaths: no` 사용을 권장해 왔습니다.



=====
====


== Helm을 사용하여 Trident 오퍼레이터를 배포하고 Trident를 설치하십시오

Trident link:https://netapp.github.io/trident-helm-chart["Helm Chart"^]를 사용하여 Trident 운영자를 배포하고 Trident를 한 번에 설치할 수 있습니다.

link:../trident-get-started/kubernetes-deploy.html["설치 개요"]을(를) 검토하여 설치 사전 요구 사항을 충족했는지, 그리고 사용 환경에 맞는 올바른 설치 옵션을 선택했는지 확인하십시오.

.시작하기 전에
link:../trident-get-started/kubernetes-deploy.html#before-you-deploy["배포 사전 요구 사항"] 외에도 link:https://v3.helm.sh/["Helm 버전 3"^]이(가) 필요합니다.


IMPORTANT: 비공개 리포지토리에 Trident를 설치할 때  `imageRegistry` 스위치를 사용하여 리포지토리 위치를 지정하는 경우 리포지토리 경로에  `/netapp/`를 사용하지 마십시오.

.단계
. Trident Helm 리포지토리 추가:
+
[source, console]
----
helm repo add netapp-trident https://netapp.github.io/trident-helm-chart
----
.  `helm install`를 사용하여 배포 및 이미지 레지스트리 위치에 이름을 지정하십시오. link:../trident-get-started/requirements.html#container-images-and-corresponding-kubernetes-versions["Trident 및 CSI 이미지"]는 하나의 레지스트리 또는 여러 레지스트리에 있을 수 있지만 모든 CSI 이미지는 동일한 레지스트리에 있어야 합니다. 예시에서  `100.2506.0`는 설치하려는 Trident 버전입니다.
+
[role="tabbed-block"]
====
.하나의 레지스트리에 있는 이미지
--
[source, console]
----
helm install <name> netapp-trident/trident-operator --version 100.2506.0 --set imageRegistry=<your-registry> --create-namespace --namespace <trident-namespace> --set nodePrep={iscsi}
----
--
.서로 다른 레지스트리에 있는 이미지
--
[source, console]
----
helm install <name> netapp-trident/trident-operator --version 100.2506.0 --set imageRegistry=<your-registry> --set operatorImage=<your-registry>/trident-operator:25.10.0 --set tridentAutosupportImage=<your-registry>/trident-autosupport:25.10 --set tridentImage=<your-registry>/trident:25.10.0 --create-namespace --namespace <trident-namespace> --set nodePrep={iscsi}
----
--
====
+

NOTE: 이미 Trident에 대한 네임스페이스를 생성한 경우  `--create-namespace` 매개변수는 추가 네임스페이스를 생성하지 않습니다.



 `helm list`을 사용하여 이름, 네임스페이스, 차트, 상태, 앱 버전 및 수정 번호와 같은 설치 세부 정보를 검토할 수 있습니다.



== 설치 중에 구성 데이터를 전달합니다

설치 중에 구성 데이터를 전달하는 방법에는 두 가지가 있습니다.

[cols="2"]
|===
| 옵션 | 설명 


| `--values` (또는 `-f`)  a| 
재정의를 포함하는 YAML 파일을 지정합니다. 이 파일은 여러 번 지정할 수 있으며 가장 오른쪽에 있는 파일이 우선 적용됩니다.



| `--set`  a| 
명령줄에서 재정의를 지정합니다.

|===
예를 들어,  `debug`의 기본값을 변경하려면 다음 명령을 실행하십시오. 여기서  `100.2506.0`는 설치하려는 Trident 버전입니다.

[source, console]
----
helm install <name> netapp-trident/trident-operator --version 100.2506.0  --create-namespace --namespace trident --set tridentDebug=true
----
nodePrep 값을 추가하려면 다음 명령을 실행하십시오.

[source, console]
----
helm install <name> netapp-trident/trident-operator --version 100.2506.0  --create-namespace --namespace trident --set nodePrep={iscsi}
----


== 구성 옵션

이 표와 Helm 차트의 일부인  `values.yaml` 파일은 키 목록과 해당 기본값을 제공합니다.


WARNING: values.yaml 파일에서 기본 선호도를 제거하지 마십시오. 사용자 지정 선호도를 제공하려면 기본 선호도를 확장하십시오.

[cols="3"]
|===
| 옵션 | 설명 | 기본값 


| `nodeSelector` | POD 할당을 위한 노드 레이블 |  


| `podAnnotations` | Pod 주석 |  


| `deploymentAnnotations` | 배포 주석 |  


| `tolerations` | POD 할당에 대한 톨러레이션 |  


| `affinity` | POD 할당에 대한 선호도  a| 
[listing]
----
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
              - arm64
              - amd64
            - key: kubernetes.io/os
              operator: In
              values:
              - linux
----

WARNING: values.yaml 파일에서 기본 선호도를 제거하지 마십시오. 사용자 지정 선호도를 제공하려면 기본 선호도를 확장하십시오.



| `tridentControllerPluginNodeSelector` | Pod에 대한 추가 노드 선택기입니다. 자세한 내용은 link:../trident-get-started/architecture.html#understanding-controller-pods-and-node-pods["컨트롤러 Pod 및 노드 Pod 이해"]을 참조하십시오. |  


| `tridentControllerPluginTolerations` | Pod에 대한 Kubernetes 허용 설정을 재정의합니다. 자세한 내용은 link:../trident-get-started/architecture.html#understanding-controller-pods-and-node-pods["컨트롤러 Pod 및 노드 Pod 이해"]을(를) 참조하십시오. |  


| `tridentNodePluginNodeSelector` | Pod에 대한 추가 노드 선택기입니다. 자세한 내용은 link:../trident-get-started/architecture.html#understanding-controller-pods-and-node-pods["컨트롤러 Pod 및 노드 Pod 이해"]을 참조하십시오. |  


| `tridentNodePluginTolerations` | Pod에 대한 Kubernetes 허용 설정을 재정의합니다. 자세한 내용은 link:../trident-get-started/architecture.html#understanding-controller-pods-and-node-pods["컨트롤러 Pod 및 노드 Pod 이해"]을(를) 참조하십시오. |  


| `imageRegistry` |  `trident-operator`,  `trident` 및 기타 이미지에 대한 레지스트리를 식별합니다. 기본값을 사용하려면 비워 두십시오. 중요: 개인 리포지토리에 Trident를 설치할 때 리포지토리 위치를 지정하기 위해  `imageRegistry` 스위치를 사용하는 경우 리포지토리 경로에  `/netapp/`를 사용하지 마십시오. | "" 


| `imagePullPolicy` |  `trident-operator`에 대한 이미지 풀 정책을 설정합니다. | `IfNotPresent` 


| `imagePullSecrets` |  `trident-operator`,  `trident` 및 기타 이미지에 대한 이미지 가져오기 비밀 키를 설정합니다. |  


| `kubeletDir` | kubelet의 내부 상태의 호스트 위치를 재정의할 수 있습니다. | `"/var/lib/kubelet"` 


| `operatorLogLevel` | Trident 운영자의 로그 레벨을  `trace`,  `debug`,  `info`,  `warn`,  `error` 또는  `fatal`로 설정할 수 있습니다. | `"info"` 


| `operatorDebug` | Trident 운영자의 로그 수준을 디버그로 설정할 수 있습니다. | `true` 


| `operatorImage` |  `trident-operator`에 대한 이미지의 완전한 재정의를 허용합니다. | "" 


| `operatorImageTag` |  `trident-operator` 이미지의 태그를 재정의할 수 있습니다. | "" 


| `tridentIPv6` | Trident가 IPv6 클러스터에서 작동하도록 설정할 수 있습니다. | `false` 


| `tridentK8sTimeout`  a| 
대부분의 Kubernetes API 작업에 대한 기본 180초 시간 초과를 재정의합니다(0이 아닌 경우 초 단위).


NOTE:  `tridentK8sTimeout` 매개변수는 Trident 설치에만 적용됩니다.
| `180` 


| `tridentHttpRequestTimeout` | HTTP 요청에 대한 기본 90초 타임아웃을 재정의하며,  `0s`는 타임아웃의 무한 기간입니다. 음수 값은 허용되지 않습니다. | `"90s"` 


| `tridentSilenceAutosupport` | Trident 주기적인 AutoSupport 보고 기능을 비활성화할 수 있습니다. | `false` 


| `tridentAutosupportImageTag` | Trident AutoSupport 컨테이너의 이미지 태그를 재정의할 수 있습니다. | `<version>` 


| `tridentAutosupportProxy` | Trident AutoSupport 컨테이너가 HTTP 프록시를 통해 홈에 전화를 걸 수 있도록 합니다. | "" 


| `tridentLogFormat` | Trident 로깅 형식을 설정합니다((`text` 또는  `json`). | `"text"` 


| `tridentDisableAuditLog` | Trident 감사 로거를 비활성화합니다. | `true` 


| `tridentLogLevel` | Trident의 로그 레벨을 `trace`, `debug`, `info`, `warn`, `error` 또는 `fatal`로 설정할 수 있습니다. | `"info"` 


| `tridentDebug` | Trident의 로그 레벨을 `debug`로 설정할 수 있습니다. | `false` 


| `tridentLogWorkflows` | 특정 Trident 워크플로우에 대해 추적 로깅 또는 로그 억제를 활성화할 수 있습니다. | "" 


| `tridentLogLayers` | 특정 Trident 레이어에 대해 추적 로깅 또는 로그 억제를 활성화할 수 있습니다. | "" 


| `tridentImage` | Trident의 이미지를 완전히 재정의할 수 있습니다. | "" 


| `tridentImageTag` | Trident의 이미지 태그를 재정의할 수 있습니다. | "" 


| `tridentProbePort` | Kubernetes 활성/준비 상태 프로브에 사용되는 기본 포트를 재정의할 수 있습니다. | "" 


| `windows` | Windows 워커 노드에 Trident를 설치할 수 있도록 합니다. | `false` 


| `enableForceDetach` | 강제 분리 기능을 활성화할 수 있습니다. 노드 상태 점검(NHC) 연산자와 통합하여 강제 분리 프로세스를 자동화할 수 있습니다. 자세한 내용은 link:../trident-reco/force-detach.html["Trident를 사용하여 상태 저장 애플리케이션의 페일오버 자동화"]을 참조하십시오. | `false` 


| `excludePodSecurityPolicy` | 운영자 포드 보안 정책을 생성에서 제외합니다. | `false` 


| `nodePrep`  a| 
Trident가 지정된 데이터 스토리지 프로토콜을 사용하여 볼륨을 관리하도록 Kubernetes 클러스터의 노드를 준비할 수 있습니다. *현재  `iscsi`만 지원됩니다.*


NOTE: OpenShift 4.19부터 이 기능을 지원하는 최소 Trident 버전은 25.06.1입니다.
|  


| `resources`  a| 
Trident 컨트롤러, 노드 및 오퍼레이터 파드에 대한 Kubernetes 리소스 제한 및 요청을 설정합니다. 각 컨테이너 및 사이드카에 대한 CPU 및 메모리를 구성하여 Kubernetes에서 리소스 할당을 관리할 수 있습니다.

리소스 요청 및 제한 구성에 대한 자세한 내용은 link:https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/["Pod 및 컨테이너에 대한 리소스 관리"^]을(를) 참조하십시오.

[WARNING]
====
* 컨테이너 또는 필드의 이름을 변경하지 마십시오.
* 들여쓰기를 변경하지 마십시오. YAML 들여쓰기는 올바른 구문 분석에 매우 중요합니다.


====
[NOTE]
====
* 기본적으로 제한은 적용되지 않으며 요청에만 기본값이 있습니다.
* 컨테이너 이름은 Pod 사양에 나타난 대로 나열됩니다.
* 사이드카는 각 메인 컨테이너 아래에 나열됩니다.
* TORC `status.CurrentInstallationParams` 필드를 확인하여 현재 적용된 값을 확인하십시오.


==== a| 
[source, yaml]
----
resources:
  controller:
    trident-main:
      requests:
        cpu: 10m
        memory: 80Mi
      limits:
          cpu:
          memory:
    csi-provisioner:
      requests:
        cpu: 2m
        memory: 20Mi
      limits:
        cpu:
        memory:
    csi-attacher:
      requests:
        cpu: 2m
        memory: 20Mi
      limits:
        cpu:
        memory:
    csi-resizer:
      requests:
        cpu: 3m
        memory: 20Mi
      limits:
        cpu:
        memory:
    csi-snapshotter:
      requests:
        cpu: 2m
        memory: 20Mi
      limits:
        cpu:
        memory:
    trident-autosupport:
      requests:
        cpu: 1m
        memory: 30Mi
      limits:
        cpu:
        memory:
  node:
    linux:
      trident-main:
        requests:
          cpu: 10m
          memory: 60Mi
        limits:
          cpu:
          memory:
      node-driver-registrar:
        requests:
          cpu: 1m
          memory: 10Mi
        limits:
          cpu:
          memory:
    windows:
      trident-main:
        requests:
          cpu: 6m
          memory: 40Mi
        limits:
          cpu:
          memory:
      node-driver-registrar:
        requests:
          cpu: 6m
          memory: 40Mi
        limits:
          cpu:
          memory:
      liveness-probe:
        requests:
          cpu: 2m
          memory: 40Mi
        limits:
          cpu:
          memory:
  operator:
    requests:
      cpu: 10m
      memory: 40Mi
    limits:
      cpu:
      memory:
----
|===