---
sidebar: sidebar 
permalink: trident-get-started/intro.html 
keywords: product overview, Trident, fsx, element, google cloud, architecture, node pod, controller pod, pods, csi, sidecar 
summary: 'Trident는 NetApp에서 관리하는 완전히 지원되는 오픈 소스 프로젝트입니다. 이 프로젝트는 Container Storage Interface(CSI)와 같은 업계 표준 인터페이스를 사용하여 컨테이너화된 애플리케이션의 영구 저장 요구 사항을 충족하도록 설계되었습니다.' 
---
= Trident에 대해 알아보십시오
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Trident는 NetApp에서 관리하는 완전히 지원되는 오픈 소스 프로젝트입니다. Container Storage Interface(CSI)와 같은 업계 표준 인터페이스를 사용하여 컨테이너화된 애플리케이션의 영구 저장 요구 사항을 충족하도록 설계되었습니다.



== Trident란 무엇입니까?

NetApp Trident를 사용하면 퍼블릭 클라우드 또는 온프레미스의 모든 주요 NetApp 스토리지 플랫폼에서 스토리지 리소스를 사용하고 관리할 수 있습니다. 여기에는 온프레미스 ONTAP 클러스터(AFF, FAS 및 ASA), ONTAP Select, Cloud Volumes ONTAP, Element 소프트웨어(NetApp HCI, SolidFire), Azure NetApp Files 및 Amazon FSx for NetApp ONTAP가 포함됩니다.

Trident는 Container Storage Interface(CSI)를 준수하는 동적 스토리지 오케스트레이터로, link:https://kubernetes.io/["Kubernetes"^]와 기본적으로 통합됩니다. Trident는 클러스터의 각 워커 노드에서 단일 Controller Pod와 Node Pod로 실행됩니다. 자세한 내용은 link:../trident-get-started/architecture.html["Trident 아키텍처"]를 참조하십시오.

Trident는 NetApp 스토리지 플랫폼을 위한 Docker 에코시스템과의 직접적인 통합도 제공합니다. NetApp Docker 볼륨 플러그인(nDVP)은 스토리지 플랫폼에서 Docker 호스트로 스토리지 리소스를 프로비저닝하고 관리하는 기능을 지원합니다. 자세한 내용은 link:../trident-docker/deploy-docker.html["Docker용 Trident 배포"]를 참조하십시오.


NOTE: Kubernetes를 처음 사용하는 경우 link:https://kubernetes.io/docs/home/["Kubernetes 개념 및 도구"^]에 익숙해져야 합니다.



== NetApp 제품과 Kubernetes 통합

NetApp의 스토리지 제품 포트폴리오는 Kubernetes 클러스터의 다양한 측면과 통합되어 고급 데이터 관리 기능을 제공함으로써 Kubernetes 배포의 기능, 성능, 가용성을 향상시킵니다.

.Amazon FSx for NetApp ONTAP
[%collapsible]
====
link:https://www.netapp.com/aws/fsx-ontap/["Amazon FSx for NetApp ONTAP"^]는 NetApp ONTAP 스토리지 운영 체제를 기반으로 하는 파일 시스템을 시작하고 실행할 수 있는 완전 관리형 AWS 서비스입니다.

====
.Azure NetApp Files
[%collapsible]
====
https://www.netapp.com/azure/azure-netapp-files/["Azure NetApp Files"^]는 NetApp이 제공하는 엔터프라이즈급 Azure 파일 공유 서비스입니다. Azure에서 기본적으로 가장 까다로운 파일 기반 워크로드를 실행할 수 있으며, NetApp에서 기대할 수 있는 성능과 풍부한 데이터 관리 기능을 제공합니다.

====
.Cloud Volumes ONTAP
[%collapsible]
====
link:https://www.netapp.com/cloud-services/cloud-volumes-ontap/["Cloud Volumes ONTAP"^]는 클라우드에서 ONTAP 데이터 관리 소프트웨어를 실행하는 소프트웨어 전용 스토리지 어플라이언스입니다.

====
.Google Cloud NetApp Volumes
[%collapsible]
====
link:https://bluexp.netapp.com/google-cloud-netapp-volumes?utm_source=GitHub&utm_campaign=Trident["Google Cloud NetApp Volumes"^]는 Google Cloud에서 제공되는 완전 관리형 파일 스토리지 서비스로, 고성능의 엔터프라이즈급 파일 스토리지를 제공합니다.

====
.Element 소프트웨어
[%collapsible]
====
https://www.netapp.com/data-management/element-software/["요소"^]를 사용하면 스토리지 관리자가 성능을 보장하고 간소화되고 효율적인 스토리지 설치 공간을 구현하여 워크로드를 통합할 수 있습니다.

====
.NetApp HCI
[%collapsible]
====
link:https://docs.netapp.com/us-en/hci/docs/concept_hci_product_overview.html["NetApp HCI"^] 일상적인 작업을 자동화하고 인프라 관리자가 더 중요한 기능에 집중할 수 있도록 함으로써 데이터 센터의 관리 및 확장을 간소화합니다.

Trident는 기본 NetApp HCI 스토리지 플랫폼에 대해 직접 컨테이너화된 애플리케이션용 스토리지 디바이스를 프로비저닝하고 관리할 수 있습니다.

====
.NetApp ONTAP
[%collapsible]
====
link:https://docs.netapp.com/us-en/ontap/index.html["NetApp ONTAP"^]는 모든 애플리케이션에 고급 데이터 관리 기능을 제공하는 NetApp 멀티프로토콜 통합 스토리지 운영 체제입니다.

ONTAP 시스템은 올플래시, 하이브리드 또는 올HDD 구성을 제공하며 온프레미스 FAS, AFA 및 ASA 클러스터, ONTAP Select 및 Cloud Volumes ONTAP 등 다양한 구축 모델을 제공합니다. Trident는 이러한 ONTAP 구축 모델을 지원합니다.

====