---
sidebar: sidebar 
permalink: trident-get-started/k8s-netapp.html 
keywords: kubernetes, netapp storage, ontap, cloud volumes ontap, santricity, element software, netapp hci, anf, azure netapp files, aws, amazon fsx 
summary: NetApp의 스토리지 제품 포트폴리오는 Kubernetes 클러스터의 다양한 측면과 통합되어 고급 데이터 관리 기능을 제공함으로써 Kubernetes 배포의 기능, 성능, 가용성을 향상시킵니다. 
---
= NetApp 제품과 Kubernetes 통합
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp의 스토리지 제품 포트폴리오는 Kubernetes 클러스터의 다양한 측면과 통합되어 고급 데이터 관리 기능을 제공함으로써 Kubernetes 배포의 기능, 성능, 가용성을 향상시킵니다.



== Trident

https://docs.netapp.com/us-en/trident/["Trident"^]는 기업이 퍼블릭 클라우드와 온프레미스 환경 내에서 그리고 클라우드 간에 Kubernetes에서 실행되는 데이터 집약적인 컨테이너화된 워크로드를 더 쉽게 관리, 보호 및 이동할 수 있도록 지원합니다. Trident는 검증되고 광범위한 NetApp 스토리지 포트폴리오의 Trident를 사용하여 퍼블릭 클라우드와 온프레미스 환경에서 영구적인 컨테이너 스토리지를 프로비저닝하고 제공합니다. 또한 스냅샷, 백업 및 복원, 활동 로그, 액티브 클로닝과 같은 고급 애플리케이션 인식 데이터 관리 기능을 풍부하게 제공하여 Kubernetes 워크로드의 데이터 보호, 재해/데이터 복구, 데이터 감사 및 마이그레이션 사용 사례를 지원합니다.



== ONTAP

ONTAP은 NetApp 멀티프로토콜 통합 스토리지 운영 체제로, 모든 애플리케이션에 고급 데이터 관리 기능을 제공합니다. ONTAP 시스템은 올플래시, 하이브리드 또는 올HDD 구성으로 제공되며, 엔지니어드 하드웨어(FAS 및 AFF), 화이트박스(ONTAP Select), 클라우드 전용(Cloud Volumes ONTAP) 등 다양한 구축 모델을 지원합니다.


NOTE: Trident는 위에 언급된 모든 ONTAP 배포 모델을 지원합니다.



== Cloud Volumes ONTAP

http://cloud.netapp.com/ontap-cloud?utm_source=GitHub&utm_campaign=Trident["Cloud Volumes ONTAP"^]는 클라우드에서 ONTAP 데이터 관리 소프트웨어를 실행하는 소프트웨어 전용 스토리지 어플라이언스입니다. Cloud Volumes ONTAP를 프로덕션 워크로드, 재해 복구, DevOps, 파일 공유 및 데이터베이스 관리에 사용할 수 있습니다. 스토리지 효율성, 고가용성, 데이터 복제, 데이터 계층화 및 애플리케이션 일관성을 제공하여 엔터프라이즈 스토리지를 클라우드로 확장합니다.



== Amazon FSx for NetApp ONTAP

https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Amazon FSx for NetApp ONTAP"^]는 NetApp ONTAP 스토리지 운영 체제를 기반으로 하는 파일 시스템을 시작하고 실행할 수 있도록 지원하는 완전 관리형 AWS 서비스입니다. FSx for ONTAP을 사용하면 익숙한 NetApp 기능, 성능 및 관리 기능을 활용하는 동시에 AWS에 데이터를 저장하는 간편성, 민첩성, 보안 및 확장성의 이점을 누릴 수 있습니다. FSx for ONTAP은 다양한 ONTAP 파일 시스템 기능과 관리 API를 지원합니다.



== Element 소프트웨어

https://www.netapp.com/data-management/element-software/["요소"^]는 스토리지 관리자가 성능을 보장하고 간소화되고 효율적인 스토리지 공간을 구현하여 워크로드를 통합할 수 있도록 지원합니다. 스토리지 관리의 모든 측면을 자동화할 수 있는 API와 결합하여 Element는 스토리지 관리자가 더 적은 노력으로 더 많은 작업을 수행할 수 있도록 합니다.



== NetApp HCI

https://www.netapp.com/virtual-desktop-infrastructure/netapp-hci/["NetApp HCI"^] 일상적인 작업을 자동화하고 인프라 관리자가 더 중요한 기능에 집중할 수 있도록 함으로써 데이터 센터의 관리 및 확장을 간소화합니다.

NetApp HCI는 Trident에서 완벽하게 지원됩니다. Trident는 기본 NetApp HCI 스토리지 플랫폼에 대해 컨테이너화된 애플리케이션용 스토리지 디바이스를 직접 프로비저닝하고 관리할 수 있습니다.



== Azure NetApp Files

https://azure.microsoft.com/en-us/services/netapp/["Azure NetApp Files"^]는 NetApp이 제공하는 엔터프라이즈급 Azure 파일 공유 서비스입니다. Azure에서 기본적으로 가장 까다로운 파일 기반 워크로드를 실행할 수 있으며, NetApp에서 기대하는 성능과 풍부한 데이터 관리 기능을 제공합니다.



== Google Cloud NetApp Volumes

https://cloud.netapp.com/cloud-volumes-service-for-gcp?utm_source=GitHub&utm_campaign=Trident["Google Cloud NetApp Volumes"^]는 NFS를 통해 NAS 볼륨을 제공하는 클라우드 네이티브 파일 서비스로, 올플래시 성능을 제공합니다. 이 서비스를 통해 기존 애플리케이션을 포함한 모든 워크로드를 GCP 클라우드에서 실행할 수 있습니다. 일관된 고성능, 즉각적인 클론 생성, 데이터 보호 및 Google Compute Engine(GCE) 인스턴스에 대한 안전한 액세스를 제공하는 완전 관리형 서비스입니다.
