---
sidebar: sidebar 
permalink: trident-concepts/provisioning.html 
keywords: provisioning, Trident 
summary: Trident에서 프로비저닝은 크게 두 단계로 구성됩니다. 첫 번째 단계는 스토리지 클래스를 적합한 백엔드 스토리지 풀 세트와 연결하는 단계로, 프로비저닝 전에 필요한 준비 작업입니다. 두 번째 단계는 볼륨 생성 자체를 포함하며, 생성 예정인 볼륨의 스토리지 클래스와 연결된 스토리지 풀 중에서 하나를 선택해야 합니다. 
---
= 프로비저닝
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Trident에서 프로비저닝은 크게 두 단계로 구성됩니다. 첫 번째 단계는 스토리지 클래스를 적합한 백엔드 스토리지 풀 세트와 연결하는 단계로, 프로비저닝 전에 필요한 준비 작업입니다. 두 번째 단계는 볼륨 생성 자체를 포함하며, 생성 예정인 볼륨의 스토리지 클래스와 연결된 스토리지 풀 중에서 하나를 선택해야 합니다.



== 스토리지 클래스 연결

백엔드 스토리지 풀을 스토리지 클래스와 연결하는 작업은 스토리지 클래스에서 요청한 속성과 해당 클래스의  `storagePools`,  `additionalStoragePools` 및  `excludeStoragePools` 목록을 모두 활용합니다. 스토리지 클래스를 생성할 때 Trident는 각 백엔드가 제공하는 속성과 풀을 스토리지 클래스에서 요청한 속성 및 풀과 비교합니다. 스토리지 풀의 속성과 이름이 요청된 모든 속성 및 풀 이름과 일치하면 Trident는 해당 스토리지 풀을 스토리지 클래스에 적합한 스토리지 풀 집합에 추가합니다. 또한 Trident는  `additionalStoragePools` 목록에 있는 모든 스토리지 풀도 해당 집합에 추가합니다. 이때 해당 스토리지 풀의 속성이 스토리지 클래스에서 요청한 속성을 전부 또는 일부 충족하지 않더라도 추가될 수 있습니다.  `excludeStoragePools` 목록을 사용하여 스토리지 풀을 스토리지 클래스에서 사용하지 않도록 재정의하거나 제거할 수 있습니다. Trident는 새 백엔드를 추가할 때마다 유사한 프로세스를 수행하여 해당 백엔드의 스토리지 풀이 기존 스토리지 클래스의 스토리지 풀 요구 사항을 충족하는지 확인하고 제외로 표시된 스토리지 풀을 제거합니다.



== 볼륨 생성

Trident는 스토리지 클래스와 스토리지 풀 간의 연결을 사용하여 볼륨을 프로비저닝할 위치를 결정합니다. 볼륨을 생성하면 Trident는 먼저 해당 볼륨의 스토리지 클래스에 대한 스토리지 풀 집합을 가져오고, 볼륨에 프로토콜을 지정한 경우 Trident는 요청된 프로토콜을 제공할 수 없는 스토리지 풀을 제거합니다(예: NetApp HCI/SolidFire 백엔드는 파일 기반 볼륨을 제공할 수 없고 ONTAP NAS 백엔드는 블록 기반 볼륨을 제공할 수 없음). Trident는 볼륨이 고르게 분산되도록 이 결과 집합의 순서를 무작위로 정렬한 다음 각 스토리지 풀에서 순차적으로 볼륨 프로비저닝을 시도합니다. 하나라도 성공하면 성공적으로 반환하고 프로세스에서 발생한 모든 실패를 로그에 기록합니다. Trident는 요청된 스토리지 클래스와 프로토콜에 사용 가능한 *모든* 스토리지 풀에서 프로비저닝에 실패한 *경우에만* 실패를 반환합니다.
