---
permalink: trident-protect/manage-authorization-access-control.html 
sidebar: sidebar 
keywords: manage, authentication, rbac 
summary: 'Trident Protect는 Kubernetes의 역할 기반 액세스 제어(RBAC) 모델을 사용합니다. Trident Protect RBAC 기능을 사용하여 리소스에 대한 액세스를 보다 세밀하게 제어할 수 있습니다.' 
---
= Trident Protect 권한 부여 및 액세스 제어 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Trident Protect는 Kubernetes 모델의 역할 기반 액세스 제어(RBAC)를 사용합니다. 기본적으로 Trident Protect는 단일 시스템 네임스페이스와 해당 기본 서비스 계정을 제공합니다. 사용자 수가 많거나 특정 보안 요구 사항이 있는 조직의 경우 Trident Protect의 RBAC 기능을 활용하여 리소스 및 네임스페이스에 대한 액세스 제어를 더욱 세밀하게 수행할 수 있습니다.

클러스터 관리자는 항상 기본 `trident-protect` 네임스페이스의 리소스에 액세스할 수 있으며 다른 모든 네임스페이스의 리소스에도 액세스할 수 있습니다. 리소스 및 애플리케이션에 대한 액세스 제어를 위해 추가 네임스페이스를 생성하고 해당 네임스페이스에 리소스와 애플리케이션을 추가해야 합니다.

참고로, 기본 `trident-protect` 네임스페이스에서는 어떤 사용자도 애플리케이션 데이터 관리 CR을 생성할 수 없습니다. 애플리케이션 데이터 관리 CR은 애플리케이션 네임스페이스에서 생성해야 합니다(권장되는 방법은 해당 애플리케이션과 동일한 네임스페이스에 애플리케이션 데이터 관리 CR을 생성하는 것입니다).

[NOTE]
====
관리자만 권한 있는 Trident Protect 사용자 지정 리소스 개체에 액세스할 수 있어야 합니다. 이러한 개체에는 다음이 포함됩니다.

* *AppVault*: 버킷 자격 증명 데이터가 필요합니다
* *AutoSupportBundle*: Trident Protect의 메트릭, 로그 및 기타 민감한 데이터를 수집합니다
* *AutoSupportBundleSchedule*: 로그 수집 일정을 관리합니다


모범 사례로, RBAC를 사용하여 권한이 있는 개체에 대한 액세스를 클러스터 관리자로 제한하십시오.

====
RBAC가 리소스 및 네임스페이스에 대한 액세스를 규제하는 방법에 대한 자세한 내용은 https://kubernetes.io/docs/reference/access-authn-authz/rbac/["Kubernetes RBAC 문서"^]을 참조하십시오.

서비스 계정에 대한 자세한 내용은 https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/["Kubernetes 서비스 계정 문서"^]을 참조하십시오.



== 예: 두 사용자 그룹에 대한 액세스 관리

예를 들어, 한 조직에 클러스터 관리자, 엔지니어링 사용자 그룹, 마케팅 사용자 그룹이 있다고 가정해 보겠습니다. 클러스터 관리자는 엔지니어링 그룹과 마케팅 그룹이 각각 자신의 네임스페이스에 할당된 리소스에만 액세스할 수 있는 환경을 구축하기 위해 다음과 같은 작업을 수행합니다.



=== 1단계: 각 그룹의 리소스를 담을 네임스페이스를 생성합니다

네임스페이스를 생성하면 리소스를 논리적으로 분리하고 해당 리소스에 대한 액세스 권한을 더 효과적으로 제어할 수 있습니다.

.단계
. 엔지니어링 그룹을 위한 네임스페이스를 생성합니다.
+
[source, console]
----
kubectl create ns engineering-ns
----
. 마케팅 그룹을 위한 네임스페이스를 생성하세요:
+
[source, console]
----
kubectl create ns marketing-ns
----




=== 2단계: 각 네임스페이스의 리소스와 상호 작용할 새 서비스 계정 생성

새 네임스페이스를 생성할 때마다 기본 서비스 계정이 제공되지만, 향후 필요에 따라 그룹 간에 권한을 더욱 세분화할 수 있도록 각 사용자 그룹별로 서비스 계정을 생성해야 합니다.

.단계
. 엔지니어링 그룹을 위한 서비스 계정을 생성하세요:
+
[source, yaml]
----
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eng-user
  namespace: engineering-ns
----
. 마케팅 그룹에 대한 서비스 계정 생성:
+
[source, yaml]
----
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mkt-user
  namespace: marketing-ns
----




=== 3단계: 각 새 서비스 계정에 대한 시크릿 생성

서비스 계정 암호는 서비스 계정 인증에 사용되며, 유출된 경우 쉽게 삭제하고 다시 생성할 수 있습니다.

.단계
. 엔지니어링 서비스 계정에 대한 암호를 생성합니다.
+
[source, yaml]
----
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: eng-user
  name: eng-user-secret
  namespace: engineering-ns
type: kubernetes.io/service-account-token
----
. 마케팅 서비스 계정에 대한 암호를 생성합니다.
+
[source, yaml]
----
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: mkt-user
  name: mkt-user-secret
  namespace: marketing-ns
type: kubernetes.io/service-account-token
----




=== 4단계: RoleBinding 객체를 생성하여 ClusterRole 객체를 각 새 서비스 계정에 바인딩합니다

Trident Protect를 설치하면 기본 ClusterRole 오브젝트가 생성됩니다. 이 ClusterRole을 서비스 계정에 바인딩하려면 RoleBinding 오브젝트를 생성하고 적용할 수 있습니다.

.단계
. ClusterRole을 엔지니어링 서비스 계정에 바인딩합니다.
+
[source, yaml]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: engineering-ns-tenant-rolebinding
  namespace: engineering-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: trident-protect-tenant-cluster-role
subjects:
- kind: ServiceAccount
  name: eng-user
  namespace: engineering-ns
----
. ClusterRole을 마케팅 서비스 계정에 바인딩합니다.
+
[source, yaml]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: marketing-ns-tenant-rolebinding
  namespace: marketing-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: trident-protect-tenant-cluster-role
subjects:
- kind: ServiceAccount
  name: mkt-user
  namespace: marketing-ns
----




=== 5단계: 권한 테스트

권한이 올바른지 테스트합니다.

.단계
. 엔지니어링 사용자가 엔지니어링 리소스에 액세스할 수 있는지 확인하십시오.
+
[source, console]
----
kubectl auth can-i --as=system:serviceaccount:engineering-ns:eng-user get applications.protect.trident.netapp.io -n engineering-ns
----
. 엔지니어링 사용자가 마케팅 리소스에 액세스할 수 없는지 확인합니다.
+
[source, console]
----
kubectl auth can-i --as=system:serviceaccount:engineering-ns:eng-user get applications.protect.trident.netapp.io -n marketing-ns
----




=== 6단계: AppVault 개체에 대한 액세스 권한 부여

백업 및 스냅샷과 같은 데이터 관리 작업을 수행하려면 클러스터 관리자가 개별 사용자에게 AppVault 객체에 대한 액세스 권한을 부여해야 합니다.

.단계
. AppVault와 시크릿 조합 YAML 파일을 생성하여 사용자에게 AppVault에 대한 액세스 권한을 부여합니다. 예를 들어, 다음 CR은 사용자에게 AppVault에 대한 액세스 권한을 부여합니다 `eng-user`:
+
[source, yaml]
----
apiVersion: v1
data:
  accessKeyID: <ID_value>
  secretAccessKey: <key_value>
kind: Secret
metadata:
  name: appvault-for-eng-user-only-secret
  namespace: trident-protect
type: Opaque
---
apiVersion: protect.trident.netapp.io/v1
kind: AppVault
metadata:
  name: appvault-for-eng-user-only
  namespace: trident-protect # Trident Protect system namespace
spec:
  providerConfig:
    azure:
      accountName: ""
      bucketName: ""
      endpoint: ""
    gcp:
      bucketName: ""
      projectID: ""
    s3:
      bucketName: testbucket
      endpoint: 192.168.0.1:30000
      secure: "false"
      skipCertValidation: "true"
  providerCredentials:
    accessKeyID:
      valueFromSecret:
        key: accessKeyID
        name: appvault-for-eng-user-only-secret
    secretAccessKey:
      valueFromSecret:
        key: secretAccessKey
        name: appvault-for-eng-user-only-secret
  providerType: GenericS3
----
. 클러스터 관리자가 네임스페이스 내 특정 리소스에 대한 액세스 권한을 부여할 수 있도록 역할 CR을 생성하고 적용합니다. 예를 들면 다음과 같습니다.
+
[source, yaml]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eng-user-appvault-reader
  namespace: trident-protect
rules:
- apiGroups:
  - protect.trident.netapp.io
  resourceNames:
  - appvault-for-enguser-only
  resources:
  - appvaults
  verbs:
  - get
----
. RoleBinding CR을 생성하고 적용하여 eng-user 사용자에게 권한을 바인딩합니다. 예시:
+
[source, yaml]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eng-user-read-appvault-binding
  namespace: trident-protect
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: eng-user-appvault-reader
subjects:
- kind: ServiceAccount
  name: eng-user
  namespace: engineering-ns
----
. 권한이 올바른지 확인합니다.
+
.. 모든 네임스페이스에 대한 AppVault 객체 정보를 검색하려고 시도합니다.
+
[source, console]
----
kubectl get appvaults -n trident-protect --as=system:serviceaccount:engineering-ns:eng-user
----
+
다음과 유사한 출력이 표시됩니다.

+
[listing]
----
Error from server (Forbidden): appvaults.protect.trident.netapp.io is forbidden: User "system:serviceaccount:engineering-ns:eng-user" cannot list resource "appvaults" in API group "protect.trident.netapp.io" in the namespace "trident-protect"
----
.. 사용자가 이제 액세스 권한이 있는 AppVault 정보를 가져올 수 있는지 테스트합니다.
+
[source, console]
----
kubectl auth can-i --as=system:serviceaccount:engineering-ns:eng-user get appvaults.protect.trident.netapp.io/appvault-for-eng-user-only -n trident-protect
----
+
다음과 유사한 출력이 표시됩니다.

+
[listing]
----
yes
----




.결과
AppVault 권한을 부여받은 사용자는 승인된 AppVault 개체를 사용하여 애플리케이션 데이터 관리 작업을 수행할 수 있어야 하며, 할당된 네임스페이스 외부의 리소스에 액세스하거나 액세스 권한이 없는 새 리소스를 생성할 수 없어야 합니다.
