---
sidebar: sidebar 
permalink: trident-protect/trident-protect-upgrade.html 
keywords: trident, protect, netapp, upgrade, new, version 
summary: Trident Protect를 최신 버전으로 업그레이드하면 새로운 기능이나 버그 수정 사항을 활용할 수 있습니다. 
---
= Trident Protect 업그레이드
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Trident Protect를 최신 버전으로 업그레이드하면 새로운 기능이나 버그 수정 사항을 활용할 수 있습니다.

[NOTE]
====
* 버전 24.10에서 업그레이드할 때 업그레이드 중에 실행되는 스냅샷이 실패할 수 있습니다. 이러한 실패는 수동 또는 예약된 향후 스냅샷 생성을 방해하지 않습니다. 업그레이드 중에 스냅샷이 실패하면 수동으로 새 스냅샷을 생성하여 애플리케이션을 보호할 수 있습니다.
+
잠재적인 오류를 방지하려면 업그레이드 전에 모든 스냅샷 일정을 비활성화한 다음 업그레이드 후에 다시 활성화할 수 있습니다. 그러나 이렇게 하면 업그레이드 기간 동안 예약된 스냅샷이 누락될 수 있습니다.

* 프라이빗 레지스트리 설치의 경우, 타겟 버전에 필요한 Helm 차트 및 이미지가 프라이빗 레지스트리에 있는지 확인하고, 사용자 지정 Helm 값이 새 차트 버전과 호환되는지 확인하십시오. 자세한 내용은 link:trident-protect-installation.html["개인 레지스트리에서 Trident Protect를 설치하세요"]를 참조하십시오.


====
Trident Protect를 업그레이드하려면 다음 단계를 수행하십시오.

.단계
. Trident Helm 리포지토리를 업데이트합니다.
+
[source, console]
----
helm repo update
----
. Trident Protect CRD를 업그레이드합니다.
+

NOTE: 25.06 이전 버전에서 업그레이드하는 경우 이 단계가 필요합니다. CRD가 이제 Trident Protect Helm 차트에 포함되어 있기 때문입니다.

+
..  `trident-protect-crds`에서  `trident-protect`로 CRD 관리를 전환하려면 다음 명령을 실행합니다.
+
[source, console]
----
kubectl get crd | grep protect.trident.netapp.io | awk '{print $1}' | xargs -I {} kubectl patch crd {} --type merge -p '{"metadata":{"annotations":{"meta.helm.sh/release-name": "trident-protect"}}}'
----
..  `trident-protect-crds` 차트의 Helm 시크릿을 삭제하려면 다음 명령을 실행하십시오.
+

NOTE: Helm을 사용하여 `trident-protect-crds` 차트를 제거하지 마십시오. 이렇게 하면 CRD 및 관련 데이터가 모두 삭제될 수 있습니다.

+
[source, console]
----
kubectl delete secret -n trident-protect -l name=trident-protect-crds,owner=helm
----


. Trident Protect 업그레이드:
+
[source, console]
----
helm upgrade trident-protect netapp-trident-protect/trident-protect --version 100.2510.0 --namespace trident-protect
----
+

NOTE:  `--set logLevel=debug`을 업그레이드 명령에 추가하여 업그레이드 중 로깅 수준을 구성할 수 있습니다. 기본 로깅 수준은 `warn`입니다. 디버그 로깅은 NetApp 지원팀이 로그 수준 변경이나 문제 재현 없이 문제를 진단하는 데 도움이 되므로 문제 해결을 위해 권장됩니다.


