---
sidebar: sidebar 
permalink: trident-reference/trident-cl.html 
keywords: command-line, options, logging, kubernetes, docker, ports 
summary: Trident는 Trident 오케스트레이터를 위한 여러 명령줄 옵션을 노출하고 특정 포트를 통해 통신합니다. 
---
= 명령줄 옵션
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Trident는 Trident 오케스트레이터에 대한 여러 명령줄 옵션을 제공합니다. 이러한 옵션을 사용하여 배포를 수정할 수 있습니다.



== 로깅

`-debug`:: 디버깅 출력을 활성화합니다.
`-loglevel <level>`:: 로깅 수준(debug, info, warn, error, fatal)을 설정합니다. 기본값은 info입니다.




== Kubernetes

`-k8s_pod`:: 이 옵션 또는 `-k8s_api_server`을 사용하여 Kubernetes 지원을 활성화합니다. 이 옵션을 설정하면 Trident가 포함된 파드의 Kubernetes 서비스 계정 자격 증명을 사용하여 API 서버에 연결합니다. 이는 Trident가 서비스 계정을 활성화한 Kubernetes 클러스터에서 파드로 실행되는 경우에만 작동합니다.
`-k8s_api_server <insecure-address:insecure-port>`:: 이 옵션 또는 `-k8s_pod`을 사용하여 Kubernetes 지원을 활성화합니다. 지정하면 Trident는 제공된 비보안 주소와 포트를 사용하여 Kubernetes API 서버에 연결합니다. 이렇게 하면 Trident를 포드 외부에 배포할 수 있지만 API 서버에 대한 비보안 연결만 지원합니다. 안전하게 연결하려면 `-k8s_pod` 옵션을 사용하여 Trident를 포드에 배포합니다.




== Docker

`-volume_driver <name>`:: Docker 플러그인을 등록할 때 사용되는 드라이버 이름. 기본값은 `netapp`입니다.
`-driver_port <port-number>`:: UNIX 도메인 소켓이 아닌 이 포트에서 수신 대기합니다.
`-config <file>`:: 필수; 백엔드 구성 파일에 이 경로를 지정해야 합니다.




== REST

`-address <ip-or-host>`:: Trident의 REST 서버가 수신 대기해야 하는 주소를 지정합니다. 기본값은 localhost입니다. localhost에서 수신 대기하고 Kubernetes 포드 내에서 실행할 때 REST 인터페이스는 포드 외부에서 직접 액세스할 수 없습니다.  `-address ""`을(를) 사용하여 포드 IP 주소에서 REST 인터페이스에 액세스할 수 있도록 합니다.
+
--

CAUTION: Trident REST 인터페이스는 127.0.0.1(IPv4의 경우) 또는 [::1](IPv6의 경우)에서만 수신 대기하고 서비스를 제공하도록 구성할 수 있습니다.

--
`-port <port-number>`:: Trident의 REST 서버가 수신 대기해야 하는 포트를 지정합니다. 기본값은 8000입니다.
`-rest`:: REST 인터페이스를 활성화합니다. 기본값은 true입니다.

